<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('budgets', function (Blueprint $table) {
            $table->id();
            $table->string('cnpj',14)->nullable();
            $table->unsignedBigInteger('numero_orcamento')->nullable();
            $table->string('digito_verificador',1)->nullable();
            $table->unsignedBigInteger('complemento')->nullable();
            $table->date('data_orcamento');
            $table->date('data_entrada')->nullable();
            $table->date('data_vistoria')->nullable();
            $table->date('data_previsao')->nullable();
            $table->date('data_aprovacao')->nullable();
            $table->date('data_entrega')->nullable();
            $table->date('data_inicio_servico')->nullable();
            $table->date('data_conclusao')->nullable();
            $table->date('data_faturamento')->nullable();
            $table->date('data_revisao')->nullable();
            $table->string('revisado',1)->nullable();
            $table->date('data_enviado')->nullable();
            $table->unsignedBigInteger('auxiliar_leve')->nullable();
            $table->unsignedBigInteger('auxiliar_media')->nullable();
            $table->unsignedBigInteger('auxiliar_alta')->nullable();
            $table->unsignedBigInteger('pintura_alta')->nullable();
            $table->unsignedBigInteger('pintura_media')->nullable();
            $table->unsignedBigInteger('pintura_leve')->nullable();
            $table->string('status_pecas'. 30)->nullable();
            $table->date('data_acabamento')->nullable();
            $table->time ('hora_desmontagem_servico')->nullable();
            $table->time('hora_auxiliar_servico')->nullable();
            $table->time('hora_mecanica_servico')->nullable();
            $table->time('hora_pintura_servico')->nullable();
            $table->time('hora_funilaria_servico')->nullable();
            $table->time('hora_acabamento_servico')->nullable();
            $table->date('data_desmontagem')->nullable();
            $table->date('data_auxiliar')->nullable();
            $table->date('data_mecanica')->nullable();
            $table->date('data_pintura')->nullable();
            $table->date('data_funilaria')->nullable();
            $table->unsignedBigInteger('client_id')->nullable();
            $table->string('nome', 100)->nullable();
            $table->string('opcao_cliente', 45)->nullable();
            $table->string('logradouro', 90)->nullable();
            $table->string('numero', 10)->nullable();
            $table->string('bairro', 50)->nullable();
            $table->string('cidade', 50)->nullable();
            $table->char('uf', 2)->nullable();
            $table->string('cep', 12)->nullable();
            $table->string('telefone', 13)->nullable();
            $table->string('celular', 13)->nullable();
            $table->string('email', 100)->nullable();
            $table->string('tipo_pessoa', 8)->nullable();
            $table->string('documento', 15)->nullable();
            $table->unsignedBigInteger('id_tipo_veiculo')->nullable();
            $table->unsignedBigInteger('id_tipo_pintura')->nullable();
            $table->unsignedBigInteger('id_marca')->nullable();
            $table->string('marca', 60)->nullable();
            $table->string('condutor', 40)->nullable();
            $table->string('id_modelo', 10)->nullable();
            $table->string('modelo', 60)->nullable();
            $table->unsignedBigInteger('id_ano_modelo')->nullable();
            $table->string('ano_modelo', 45)->nullable();
            $table->longText('ano_modelo_digitado')->nullable();
            $table->decimal('valor_mercado', 12,2)->nullable();
            $table->string('placa', 8)->nullable();
            $table->string('cor', 13)->nullable();
            $table->string('codigo_cor', 15)->nullable();
            $table->unsignedBigInteger('quantidade_cor')->nullable();
            $table->unsignedBigInteger('km')->nullable();
            $table->string('chassi', 20)->nullable();
            $table->char('macaco', 1)->nullable();
            $table->string('chave_de_roda', 1)->nullable();
            $table->string('triangulo', 1)->nullable();
            $table->string('som', 1)->nullable();
            $table->string('estepe', 1)->nullable();
            $table->unsignedBigInteger('combustivel')->default('0');
            $table->string('frente_som_cliente', 1)->nullable();
            $table->decimal('total_pecas', 12,2)->nullable();
            $table->string('desconto_pecas',12,2)->nullable();
            $table->string('desconto_autorizado',12,2)->nullable();
            $table->string('total_mao_de_obra',12,2)->nullable();
            $table->string('desconto_mao_de_obra',12,2)->nullable();
            $table->unsignedBigInteger('id_funcionario')->nullable();
            $table->decimal('desconto_funcionario', 12,2)->default('0.00');
            $table->unsignedBigInteger('parcela_funcionario')->nullable();
            $table->unsignedBigInteger('id_seguradora')->nullable();
            $table->string('sinistro', 45)->nullable();
            $table->string('orcamento_seguradora', 45)->nullable();
            $table->decimal('franquia', 12,2)->nullable();
            $table->string('cliente_segurado', 1)->nullable();
            $table->string('orcamento_complementar', 1)->nullable();
            $table->string('orcamento_reprovado', 1)->nullable();
            $table->string('carro_com_cliente', 1)->nullable();
            $table->string('notas_cliente',90)->nullable();
            $table->string('notas_cia',90)->nullable();
            $table->longText('observacao')->nullable();
            $table->unsignedBigInteger('id_funilaria_funcionario')->nullable();
            $table->time('hora_funilaria_comissao')->nullable();
            $table->string('valor_funilaria_comissao', 12,2)->nullable();
            $table->longText('observacao_funilaria')->nullable();
            $table->unsignedBigInteger('id_pintura_funcionario')->nullable();
            $table->unsignedBigInteger('pecas_pintura_comissao')->nullable();
            $table->decimal('valor_pintura_comissao', 12,2)->nullable();
            $table->longText('observacao_pintura')->nullable();
            $table->unsignedBigInteger('id_mecanica_funcionario')->nullable();
            $table->string('hora_mecanica_comissao', 5)->nullable();
            $table->decimal('valor_mecanica_comissao', 12,2)->nullable();
            $table->longText('observacao_mecanica')->nullable();
            $table->unsignedBigInteger('id_auxiliar_funcionario')->nullable();
            $table->unsignedBigInteger('pecas_auxiliar_comissao')->nullable();
            $table->decimal('valor_auxiliar_comissao', 12,2)->nullable();
            $table->longText('observacao_auxiliar')->nullable();
            $table->unsignedBigInteger('id_desm_montagem_funcionario')->nullable();
            $table->string('hora_desm_montagem_comissao', 5)->nullable();
            $table->decimal('valor_desm_montagem_comissao', 12,2)->nullable();
            $table->longText('observacao_desm_montagem')->nullable();
            $table->unsignedBigInteger('id_acabamento_funcionario')->nullable();
            $table->unsignedBigInteger('tinta')->nullable();
            $table->unsignedBigInteger('primer')->nullable();
            $table->unsignedBigInteger('verniz')->nullable();
            $table->string('hora_acabamento_comissao',5)->nullable();
            $table->string('valor_acabamento_comissao',12,2)->nullable();
            $table->string('valor_total_comissao',12,2)->nullable();
            $table->longText('observacao_acabamento')->nullable();
            $table->longText('observacoes')->nullable();
            $table->longText('observacao_externa')->nullable();
            $table->decimal('total_pecas_autorizado', 12,2)->nullable();
            $table->decimal('funilaria_orcado', 12,2)->nullable();
            $table->decimal('funilaria_autorizado',12,2)->nullable();
            $table->decimal('pintura_orcado', 12,2)->nullable();
            $table->decimal('pintura_autorizado', 12,2)->nullable();
            $table->decimal('mecanica_orcado', 12,2)->nullable();
            $table->decimal('mecanica_autorizado', 12,2)->nullable();
            $table->decimal('terceiro_orcado', 12,2)->nullable();
            $table->decimal('terceiro_autorizado', 12,2)->nullable();
            $table->decimal('eletrica_orcado', 12,2)->nullable();
            $table->decimal('eletrica_autorizado', 12,2)->nullable();
            $table->decimal('desm_montagem_orcado', 12,2)->nullable();
            $table->decimal('desm_montagem_autorizado', 12,2)->nullable();
            $table->decimal('acabamento_orcado', 12,2)->nullable();
            $table->decimal('acabamento_autorizado', 12,2)->nullable();
            $table->decimal('material_pintura_orcado', 12,2)->nullable();
            $table->decimal('material_pintura_autorizado', 12,2)->nullable();
            $table->decimal('percentual_iss_terceiro', 12,2)->nullable();
            $table->decimal('valor_iss_terceiro', 12,2)->nullable();
            $table->decimal('total_comissao_material_pintura', 12,2)->nullable();
            $table->decimal('total_mao_de_obra_autorizado', 12,2)->nullable();
            $table->string('total_confirmado', 1)->nullable();
            $table->decimal('total_geral_orcado', 12,2)->nullable();
            $table->decimal('total_geral_autorizado', 12,2)->nullable();
            $table->decimal('percentual_reparacao', 12,2)->nullable();
            $table->string('caixa_porta_direita', 1)->nullable();
            $table->string('paralama_dianteiro_direito', 1)->nullable();
            $table->string('porta_direita_dianteira', 1)->nullable();
            $table->string('porta_direita_traseira', 1)->nullable();
            $table->string('paralama_traseiro_direito', 1)->nullable();
            $table->string('parachoque_dianteiro', 1)->nullable();
            $table->string('painel_dianteiro', 1)->nullable();
            $table->string('capo', 1)->nullable();
            $table->string('para_brisa', 1)->nullable();
            $table->string('teto', 1)->nullable();
            $table->string('para_brisa_traseiro', 1)->nullable();
            $table->string('capo_traseiro', 1)->nullable();
            $table->string('painel_traseiro', 1)->nullable();
            $table->string('parachoque_traseiro', 1)->nullable();
            $table->string('paralama_dianteiro_esquerdo', 1)->nullable();
            $table->string('porta_esquerda_dianteira', 1)->nullable();
            $table->string('porta_esquerda_traseira', 1)->nullable();
            $table->string('paralama_traseiro_esquerdo', 1)->nullable();
            $table->string('caixa_porta_esquerda', 1)->nullable();
            $table->string('tipo_usuario_inclusao', 7)->nullable();
            $table->string('peca_dano_pri', 45)->nullable();
            $table->string('peca_dano_seg', 45)->nullable();
            $table->string('peca_dano_ter', 45)->nullable();
            $table->string('peca_dano_qua', 45)->nullable();
            $table->string('peca_dano_qui', 45)->nullable();
            $table->string('cb_peca_dano_pri', 1)->nullable();
            $table->string('cb_peca_dano_seg', 1)->nullable();
            $table->string('cb_peca_dano_ter', 1)->nullable();
            $table->string('cb_peca_dano_qua', 1)->nullable();
            $table->string('cb_peca_dano_qui', 1)->nullable();
            $table->unsignedBigInteger('importado_pre_orcamento')->nullable();
            $table->unsignedBigInteger('id_forma_pagamento')->nullable();
            $table->string('forma_pagto', 9)->nullable();
            $table->string('mostrar_condicao_pagamento', 3)->nullable();
            $table->string('faturar_orcamento', 1)->nullable();
            $table->longText('observacao_checklist')->nullable();
            $table->string('ck_teto_sel', 1)->nullable();
            $table->string('ck_soleira_esquerdo_sel', 1)->nullable();
            $table->string('ck_para_choque_traseiro_sel', 1)->nullable();
            $table->string('ck_painel_traseiro_sel', 1)->nullable();
            $table->string('ck_tampa_traseira_sel', 1)->nullable();
            $table->string('ck_para_lama_esquerdo_sel', 1)->nullable();
            $table->string('ck_porta_dianteira_esquerdo_sel', 1)->nullable();
            $table->string('ck_porta_traseira_esquerdo_sel', 1)->nullable();
            $table->string('ck_lateral_traseira_esquerdo_sel', 1)->nullable();
            $table->string('ck_soleira_direito_sel', 1)->nullable();
            $table->string('ck_para_choque_dianteiro_sel', 1)->nullable();
            $table->string('ck_painel_dianteiro_sel', 1)->nullable();
            $table->string('ck_capo_sel', 1)->nullable();
            $table->string('ck_para_lama_direito_sel', 1)->nullable();
            $table->string('ck_porta_dianteira_direito_sel', 1)->nullable();
            $table->string('ck_porta_traseira_direito_sel', 1)->nullable();
            $table->string('ck_lateral_traseira_direito_sel', 1)->nullable();
            $table->char('ck_parabrisa_dianteiro_sel', 1)->default('S');
            $table->char('ck_parabrisa_traseiro_sel', 1)->default('S');
            $table->char('ck_vidro_dianteiro_direito_sel', 1)->default('S');
            $table->char('ck_vidro_dianteiro_esquerdo_sel', 1)->default('S');
            $table->char('ck_vidro_traseiro_direito_sel', 1)->default('S');
            $table->char('ck_vidro_traseiro_esquerdo_sel', 1)->default('S');
            $table->char('ck_retrovisor_direito_sel', 1)->default('S');
            $table->char('ck_retrovisor_esquerdo_sel', 1)->default('S');
            $table->char('ck_farol_dianteiro_direito_sel', 1)->default('S');
            $table->char('ck_farol_dianteiro_esquerdo_sel', 1)->default('S');
            $table->char('ck_farol_traseiro_direito_sel', 1)->default('S');
            $table->char('ck_farol_traseiro_esquerdo_sel', 1)->default('S');
            $table->char('ck_pneu_dianteiro_direito_sel', 1)->default('S');
            $table->char('ck_pneu_dianteiro_esquerdo_sel', 1)->default('S');
            $table->char('ck_pneu_traseiro_direito_sel', 1)->default('S');
            $table->char('ck_pneu_traseiro_esquerdo_sel', 1)->default('S');
            $table->string('ck_calota_dianteiro_direito_sel', 1)->nullable();
            $table->string('ck_calota_dianteiro_esquerdo_sel', 1)->nullable();
            $table->string('ck_calota_traseiro_direito_sel', 1)->nullable();
            $table->string('ck_calota_traseiro_esquerdo_sel', 1)->nullable();
            $table->string('ck_roda_dianteiro_direito_sel', 1)->nullable();
            $table->string('ck_roda_dianteiro_esquerdo_sel', 1)->nullable();
            $table->string('ck_roda_traseiro_direito_sel', 1)->nullable();
            $table->string('ck_roda_traseiro_esquerdo_sel', 1)->nullable();
            $table->string('ck_fluido_arrefecimento_sel', 1)->nullable();
            $table->string('ck_fluido_freio_sel', 1)->nullable();
            $table->string('ck_fluido_direcao_sel', 1)->nullable();
            $table->string('ck_escapamento_sel', 1)->nullable();
            $table->string('ck_bateria_sel', 1)->nullable();
            $table->string('ck_extintor_sel', 1)->nullable();
            $table->string('ck_palhetas_dianteiras_sel', 1)->nullable();
            $table->string('ck_piscas_dianteiros_sel', 1)->nullable();
            $table->string('ck_lubrificante_motor_sel', 1)->nullable();
            $table->string('ck_filtro_oleo_sel', 1)->nullable();
            $table->string('ck_filtro_ar_motor_sel', 1)->nullable();
            $table->string('ck_filtro_combustivel_sel', 1)->nullable();
            $table->string('ck_higienizacao_ar_condicionado_sel', 1)->nullable();
            $table->string('ck_limpeza_veiculo_sel', 1)->nullable();
            $table->string('ck_documento_sel', 1)->nullable();
            $table->string('ck_manual_veiculo_sel', 1)->nullable();
            $table->string('ck_luzes_painel_sel', 1)->nullable();
            $table->string('ck_tapetes_sel', 1)->nullable();
            $table->string('ck_bancos_sel', 1)->nullable();
            $table->string('ck_acendedor_sel', 1)->nullable();
            $table->string('ck_limpador_parabrisa_sel', 1)->nullable();
            $table->string('ck_radio_sel', 1)->nullable();
            $table->string('ck_sensor_estacionamento_sel', 1)->nullable();
            $table->string('ck_antena_sel', 1)->nullable();
            $table->string('ck_auto_falante_sel', 1)->nullable();
            $table->string('ck_piscas_traseiros_sel', 1)->nullable();
            $table->string('ck_palheta_traseiro_sel', 1)->nullable();
            $table->string('ck_chave_reserva_sel', 1)->nullable();
            $table->string('ck_adesivos_sel', 1)->nullable();
            $table->string('ck_ponteira_escapamento_sel', 1)->nullable();
            $table->string('ck_motor_sel', 1)->nullable();
            $table->string('ck_triangulo_sel', 1)->nullable();
            $table->string('ck_estepe_sel', 1)->nullable();
            $table->string('ck_chave_roda_sel', 1)->nullable();
            $table->string('ck_ferramentas_sel', 1)->nullable();
            $table->string('ck_macaco_sel', 1)->nullable();
            $table->string('ck_cadeira_bebe_sel', 1)->nullable();
            $table->string('ck_assento_infantil_sel', 1)->nullable();
            $table->string('ck_gps_sel', 1)->nullable();
            $table->unsignedBigInteger('codigo_prisma')->nullable();
            $table->string('cor_prisma', 10)->nullable();
            $table->string('ocultar_painel', 1)->nullable();
            $table->string('data_cadastro')->nullable();
            $table->date('data_ultima_alteracao')->nullable();
            

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('budgets');
    }
};
